version: '2.1'

services:
  users-db:
    container_name: users-db
    build: ./services/users/src/database
    ports:
      - '5433:5432' # expose ports - HOST:CONTAINER
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    healthcheck:
      test: exit 0

  tasks-db:
    container_name: tasks-db
    build: ./services/tasks/src/database
    ports:
      - '5434:5432' # expose ports - HOST:CONTAINER
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    build: ./services/users/
    volumes:
      - './services/users:/usr/src/app'
      - './services/users/package.json:/usr/src/package.json'
    ports:
      - '3000:3000' # expose ports - HOST:CONTAINER
    environment:
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - NODE_ENV=${NODE_ENV}
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db

  tasks-service:
    container_name: tasks-service
    build: ./services/tasks/
    volumes:
      - './services/tasks:/usr/src/app'
      - './services/tasks/package.json:/usr/src/package.json'
    ports:
      - '3001:3000' # expose ports - HOST:CONTAINER
    environment:
      - DATABASE_URL=postgres://postgres:postgres@tasks-db:5432/tasks_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@tasks-db:5432/tasks_test
      - NODE_ENV=${NODE_ENV}
    depends_on:
      tasks-db:
        condition: service_healthy
    links:
      - tasks-db

  web:
    container_name: web
    build: ./services/web/
    volumes:
      - './services/web:/usr/src/app'
      - './services/web/package.json:/usr/src/package.json'
    ports:
      - '3007:3006' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      users-service:
        condition: service_started
      tasks-service:
        condition: service_started
    links:
      - users-service
      - tasks-service
